# Generated by Django 3.1.4 on 2021-01-10 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hall_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=101, unique=True)),
                ('room_type', models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=12)),
                ('category', models.CharField(choices=[('Double Bed', 'Double Bed'), ('Single Bed', 'Single Bed'), ('Triple Bed', 'Triple Bed')], max_length=10)),
                ('cost', models.IntegerField(default=2000)),
                ('image', models.ImageField(default='avathar.png', upload_to='Image/')),
            ],
        ),
        migrations.CreateModel(
            name='Exfd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('FM', 'FeMale')], max_length=10)),
                ('lang', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Urdhu', 'Urdhu')], max_length=10)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phno', models.CharField(max_length=10, null=True)),
                ('impf', models.ImageField(default='avathar.png', upload_to='Profile/')),
                ('d', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book_hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('persons', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall.hall_details')),
            ],
        ),
    ]
