# Generated by Django 3.1.4 on 2021-01-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall_details',
            old_name='room_type',
            new_name='hall_type',
        ),
        migrations.RemoveField(
            model_name='book_hall',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='hall_details',
            name='category',
        ),
        migrations.AddField(
            model_name='hall_details',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Exfd',
        ),
    ]
